export const cityOptions = [
  { name: "London", timezone: "Europe/London" },
  { name: "New York", timezone: "America/New_York" },
  { name: "Tokyo", timezone: "Asia/Tokyo" },
  { name: "Paris", timezone: "Europe/Paris" },
  { name: "Beijing", timezone: "Asia/Shanghai" },
  { name: "Sydney", timezone: "Australia/Sydney" },
  { name: "Moscow", timezone: "Europe/Moscow" },
  { name: "Dubai", timezone: "Asia/Dubai" },
  { name: "Toronto", timezone: "America/Toronto" },
  { name: "São Paulo", timezone: "America/Sao_Paulo" },
  { name: "Los Angeles", timezone: "America/Los_Angeles" },
  { name: "Berlin", timezone: "Europe/Berlin" },
  { name: "Cairo", timezone: "Africa/Cairo" },
  { name: "Johannesburg", timezone: "Africa/Johannesburg" },
  { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Mexico City", timezone: "America/Mexico_City" },
  { name: "Seoul", timezone: "Asia/Seoul" },
  { name: "Bangkok", timezone: "Asia/Bangkok" },
  { name: "Istanbul", timezone: "Europe/Istanbul" },
  { name: "Rome", timezone: "Europe/Rome" },
  { name: "Chicago", timezone: "America/Chicago" },
  { name: "Madrid", timezone: "Europe/Madrid" },
  { name: "Amsterdam", timezone: "Europe/Amsterdam" },
  { name: "Lagos", timezone: "Africa/Lagos" },
  { name: "Singapore", timezone: "Asia/Singapore" },
  { name: "Jakarta", timezone: "Asia/Jakarta" },
  { name: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
  { name: "Tehran", timezone: "Asia/Tehran" },
  { name: "Damascus", timezone: "Asia/Damascus" },
  { name: "Delhi", timezone: "Asia/Kolkata" }
];
